### ISSUE TITLE
Duda sobre el tipo de componente

### ISSUE THREAD

**Issue by ffiguereo** [josealvaradoo/edgrid-react#1]
¿Porque declaras los componentes como `PureComponent` sí no implementas el método `shouldComponentUpdate()` y el componente no tiene una estructura compleja?

```jsx
import React, {PureComponent} from 'react';

export default class EDcontainer extends PureComponent {
  render() {
    return(
      <div>
        {this.props.children}
      </div>
    )
  }
}
```

**Comment by josealvaradoo** [comment]
Tienes razón. Lo he vuelto a colocar como un componente _no puro_.
Gracias 👍
